on:
  workflow_call:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        show-progress: false

    - name: Setup Node.js
      uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
      with:
        node-version-file: .nvmrc
        check-latest: true
        cache: yarn

    - name: Install
      run: yarn install --immutable

    - name: Compile file and build
      run: yarn build

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: build
        path: dist
        if-no-files-found: error
