name: Dependency Review
on:
  pull_request:
    branches:
    - main
    paths-ignore:
    - "**/*.md"

jobs:
  dependency-review:
    name: Dependencies Review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        show-progress: false
    - name: Dependency Review
      uses: actions/dependency-review-action@5a2ce3f5b92ee19cbb1541a4984c76d921601d7c # v4.3.4
      with:
        fail-on-scopes: runtime,unknown
        comment-summary-in-pr: on-failure
