name: Main

on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
    branches:
    - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  tests:
    uses: ./.github/workflows/tests.yml
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    uses: ./.github/workflows/build.yml

  npm-publish:
    if: github.ref_type == 'tag'
    needs:
      - tests
      - lint
      - build
    uses: ./.github/workflows/publish.yml
    secrets:
      token: ${{ secrets.NPM_TOKEN }}
