name: Publish

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        show-progress: false

    - name: Setup Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
      with:
        node-version-file: .nvmrc
        check-latest: true
        cache: npm
      
    - name: Download Build Artifacts
      uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4.1.9
      with:
        name: build
        path: dist
      
    - name: Publish
      run: yarn npm publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.token }}
